### ISSUE TITLE
RFC: Code Embedding Analysis Tool

### ISSUE THREAD

**Issue by aygp-dr** [defrecord/anthropic-quickstarts#8]
# Code Embedding Analysis Tool RFC

## Overview
Implement a tool to analyze Python files, generate embeddings, and store them in PostgreSQL for semantic code search and analysis.

## Background
We have many Python files in the codebase that could benefit from semantic search and similarity analysis. By generating and storing embeddings, we can enable:
- Semantic code search
- Code similarity detection
- Duplicate functionality detection
- Code organization insights

### 1. Database Schema
```sql
CREATE TABLE code_embeddings (
    id SERIAL PRIMARY KEY,
    file_path TEXT NOT NULL,
    file_hash TEXT NOT NULL,  -- For detecting changes
    content TEXT NOT NULL,    -- Original file content
    embedding vector(1536),   -- Using Postgres vector extension
    metadata JSONB,          -- Additional metadata
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(file_path)
);

-- Index for similarity search
CREATE INDEX code_embeddings_embedding_idx ON code_embeddings 
USING ivfflat (embedding vector_cosine_ops);
```

#### File Processor
```python
class PythonFileProcessor:
    def __init__(self, db_config: Dict[str, Any]):
        self.db = PostgresConnection(db_config)
        self.model = self._init_embedding_model()

    def process_file(self, file_path: str) -> Dict[str, Any]:
        content = self._read_file(file_path)
        embedding = self._generate_embedding(content)
        metadata = self._extract_metadata(content)
        return self._store_embedding(file_path, content, embedding, metadata)

    def _generate_embedding(self, content: str) -> List[float]:
        # Use local LLM via Ollama for embeddings
        return self.model.generate_embedding(content)
```

#### Embedding Generator
```python
class EmbeddingGenerator:
    def __init__(self, model_name: str = "codellama"):
        self.model_name = model_name
        self.ollama_url = "http://host.docker.internal:11435"

    async def generate_embedding(self, text: str) -> List[float]:
        response = await self._call_ollama(text)
        return response["embedding"]
```

#### Database Manager
```python
class DatabaseManager:
    def __init__(self, config: Dict[str, Any]):
        self.pool = asyncpg.create_pool(
            database=config["PGDATABASE"],
            user=config["PGUSER"],
            password=config["PGPASSWORD"],
            host=config["PGHOST"],
            port=config["PGPORT"]
        )

    async def store_embedding(self, data: Dict[str, Any]) -> None:
        async with self.pool.acquire() as conn:
            await conn.execute(
                """INSERT INTO code_embeddings 
                   (file_path, file_hash, content, embedding, metadata)
                   VALUES ($1, $2, $3, $4, $5)
                   ON CONFLICT (file_path) 
                   DO UPDATE SET embedding = $4, metadata = $5""",
                data["file_path"], data["file_hash"],
                data["content"], data["embedding"], data["metadata"]
            )
```

### 3. CLI Interface
```python
@click.group()
def cli():
    """Code Embedding Analysis Tool"""
    pass

@cli.command()
@click.argument("path", type=click.Path(exists=True))
@click.option("--recursive/--no-recursive", default=True)
@click.option("--model", default="codellama")
def analyze(path: str, recursive: bool, model: str):
    """Analyze Python files and generate embeddings."""
    processor = PythonFileProcessor(model)
    files = get_python_files(path, recursive)
    for file in files:
        processor.process_file(file)

@cli.command()
@click.argument("query")
@click.option("--limit", default=5)
def search(query: str, limit: int):
    """Search code using semantic similarity."""
    searcher = CodeSearcher()
    results = searcher.search(query, limit)
    display_results(results)
```

### 4. Key Features

1. **File Analysis**
   - AST parsing for structure analysis
   - Dependency extraction
   - Function/class identification
   - Comment and docstring extraction

2. **Embedding Generation**
   - Local model usage via Ollama
   - Configurable chunking strategies
   - Batched processing

3. **Search Capabilities**
   - Semantic code search
   - Similar code detection
   - Function similarity analysis
   - Cross-project code reuse detection

4. **Monitoring & Maintenance**
   - File change detection
   - Embedding updates
   - Usage analytics
   - Performance metrics

## Implementation Plan

1. **Phase 1: Core Infrastructure**
   - Database schema setup
   - Basic file processing
   - Embedding generation

2. **Phase 2: Analysis Features**
   - AST parsing
   - Metadata extraction
   - Similarity search

3. **Phase 3: CLI & Integration**
   - Command-line interface
   - Configuration management
   - Documentation

4. **Phase 4: Advanced Features**
   - Batch processing
   - Incremental updates
   - Search optimization

## Acceptance Criteria

- [ ] Successfully process all Python files in the tools directory
- [ ] Generate and store embeddings with metadata
- [ ] Implement semantic search with >80% accuracy
- [ ] Support incremental updates
- [ ] Include comprehensive documentation
- [ ] Add test suite with >90% coverage

## Questions

1. Should we support multiple embedding models?
2. What is the optimal chunk size for code analysis?
3. How should we handle very large files?
4. What similarity threshold should we use?

## Next Steps

1. Set up database schema
2. Implement core file processor
3. Add embedding generation
4. Create basic CLI
5. Add tests and documentation
